# Generated by Django 4.2 on 2023-04-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_working_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_day',
            name='date',
            field=models.DateField(),
        ),
    ]
